### ISSUE TITLE
NixOS package/module

### ISSUE THREAD

**Issue by phile314** [hercules-ci/legacy-old-hercules#33]
Having a NixOS package/module would make it easier to try out hercules. I saw that this is already mentioned in #5 , but I think this warrants it's own issue.

I noticed that some dependencies (opaleye-gen) are not on hackage yet, I assume this is a blocker for this?

**Comment by expipiplus1** [comment]
@phile314, you should be able to just run `nix-build` in the `backend` directory to get the binary. 

It would certainly be a good thing to get Hercules into nixpkgs proper, however at the moment it's not really ready to do anything interesting, it's very much still under development!

**Comment by domenkozar** [comment]
Agreed. I think I'll eventually just add a module here, so people can quick-start using it (for development).

**Comment by domenkozar** [comment]
For opaleye-gen see https://github.com/folsen/opaleye-gen/issues/8
